project:
  title: "demo_collab_meeting"
  type: website
format: 
    html: default
    pdf: default
    docx: default
    mediawiki: default
author: "Christian Haack"
affiliation: ECP, TU Munich
affiliation-url: https://www.ph.nat.tum.de/cosmic-particles/experimental-physics-with-cosmic-particles/
