---
title: "Quarto"
author: "Christian Haack"  
bibliography: references.bib
csl: nature.csl
comments:
  hypothesis: true
---

# Introduction
[Quarto](https://quarto.org) is an open-source publishing system based on pandoc with focus on scientific writing.

**tl/dr**: jupyter notebooks $\Rightarrow$ scientific document

# Features

## Output types
* Write in markdown, render to various output formats. Including:
    + html
    + pdf (using pdflatex, luatex, wkhtmltopdf, ...)
    + presentations (Powerpoint, revealjs, Beamer)
    + Word
    + Markdown
    + ...

## Equations

LaTeX-style equation syntax is fully supported.
Inline $\alpha = \frac{1}{137}$ or display math:
$$
E = mc^2
$$

For HTML outputs, rendered e.g. using mathjax, katex, mathml, ...

## Computations
Quarto allows integrates jupyter to support computation using essentially all languages that are supported by jupyter (python, julia, R, ...). It allows allows for interactive content produces by various interactivity libraries.

::: {.content-visible when-format="html:js"}
## Interactive Plot 
This plot won't render in PDF, but we can hide it from this format.

```{python}
# | fig-cap: "Interactive plot using plotly"
# | echo: false

import plotly.express as px
import plotly.io as pio

df = px.data.iris()
fig = px.scatter(
    df,
    x="sepal_width",
    y="sepal_length",
    color="species",
    marginal_y="violin",
    marginal_x="box",
    trendline="ols",
    template="simple_white",
)
fig.show()
```
:::

::: {.content-visible when-format="pdf"}
This will show only in the PDF output.

```{python}
# | fig-cap: "Static plot using plotly"
# | echo: false

from IPython.display import Image

Image(fig.to_image(format="png", engine="orca"))
```
:::

## Publishing
Quarto includes convenience functions to publish documents to various targets. Most interesting for us is github pages:

```
quarto publish gh-pages

```

## Citations
Citation from *.bib files is fully supported.
Our^[Or do you prefer [@KM3NeT]?] favorite paper [@IceCube]


## Collaborative Writing
No builtin collaborative writing support. Can use of course use github, or any other tool that allows collaboration on text documents.
However, convenient integration of annotation tools like [hypothes.is](https://web.hypothes.is/), [giscus](https://giscus.app/) or [utterances](https://utteranc.es/). (Here using hypothes.is)


## Applications in IceCube

* Technical Reports
* "Analysis Wikis"
* Approved Plots (no need to use webplotdigitizer..)
* Papers??

## References

::: {#refs}
:::